name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start MLflow server
        run: |
          mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root ./mlruns &
          sleep 10 
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000

      - name: run pipeline
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          dvc repro

      - name: Run model tests
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          python -m unittest tests/test_model.py